name: build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for following branches
  push:
    branches:
      - main
      - main-*
  pull_request:
    branches:
      - main-*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out
        uses: actions/checkout@v2

      # Uses the Cache for Maven
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Uses JDK 11 for compilation
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # Compile & Test & Calculate Coverage
      - name: Compile & Test
        run: mvn clean test jacoco:report -B -P github-actions

      # Submit the code coverage to coveralls.io
      - name: Submit Code Coverage
        if: github.event_name != 'pull_request'
        run: mvn coveralls:report -B -P github-actions -D repoToken=${{ secrets.COVERALLS_TOKEN }}
